src/Entity/Chambre.php
<?php

namespace App\Entity;

use App\Repository\ChambreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ChambreRepository::class)]
class Chambre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(length: 255)]
    private ?string $description_courte = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description_longue = null;

    #[ORM\Column(length: 255)]
    private ?string $photo = null;

    #[ORM\Column]
    private ?float $prix_journalier = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    #[ORM\OneToMany(mappedBy: 'chambre', targetEntity: Commande::class, orphanRemoval: true)]
    private Collection $commandes;

    public function __toString()
    {
        return $this->titre; 
    }

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescriptionCourte(): ?string
    {
        return $this->description_courte;
    }

    public function setDescriptionCourte(string $description_courte): static
    {
        $this->description_courte = $description_courte;

        return $this;
    }

    public function getDescriptionLongue(): ?string
    {
        return $this->description_longue;
    }

    public function setDescriptionLongue(string $description_longue): static
    {
        $this->description_longue = $description_longue;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }

    public function getPrixJournalier(): ?float
    {
        return $this->prix_journalier;
    }

    public function setPrixJournalier(float $prix_journalier): static
    {
        $this->prix_journalier = $prix_journalier;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): static
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): static
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setChambre($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): static
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getChambre() === $this) {
                $commande->setChambre(null);
            }
        }

        return $this;
    }
}

templates/app/actualites.html.twig
{% extends "base.html.twig" %}

{% block title %}Actualités
{% endblock %}
{% block body %}
	<div class="container">
		<h1 class="border-bottom py-2 text-center my-4 text-uppercase" style="color:#B8860B">Actualités</h1>

		<div class="row">
			{% for article in articles %}
				<div class="col-md-4">
					<div class="card my-3 bg-light">
						<img src="{{ article.urlToImage }}" class="card-img-top rounded" alt="Image non disponible">
						<div class="card-body">
							<h5 class="card-title">{{ article.title }}</h5>
							<p class="card-text">{{ article.description }}</p>
						</div>
						<ul class="list-group list-group-flush">
							<li class="list-group-item">
								<strong>Auteur:</strong>
								{% if article.author %}
									{{ article.author }}
								{% else %}
									Auteur inconnu
								{% endif %}
							</li>
							<li class="list-group-item">
								<strong>Date de publication:</strong>
								{{ article.publishedAt }}
							</li>
						</ul>
						<div class="card-body">
							<a href="{{ article.url }}" class="btn btn-css">Lire l'article entier</a>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
{% endblock %}

templates/app/cgdv.html.twig
{% extends "base.html.twig" %}

{% block title %}Conditions Générales de Ventes
{% endblock %}

{% block body %}
	<div class="container mt-5">
		<h1 class="text-center my-4 text-uppercase border-bottom py-2" style="color:#B8860B">Conditions Générales de Ventes</h1>

		<div class="row">
			<div class="col-md-8 offset-md-2">
				<h2 class=" my-4 py-2" style="color:#B8860B">1. Objet</h2>
				<p>Les présentes conditions générales de vente (ci-après les "CGV") régissent les relations contractuelles entre l'hôtel HotelHouse (ci-après le "Vendeur") et ses clients (ci-après les "Clients") dans le cadre de la réservation et de la fourniture de services d'hébergement.</p>
				<p>En passant une réservation, le Client reconnaît avoir pris connaissance et accepté les présentes CGV.</p>

				<h2 class=" my-4 py-2" style="color:#B8860B">2. Réservation</h2>
				<p>La réservation peut être effectuée en ligne via notre site web ou par téléphone auprès de notre service de réservations. Le Client doit fournir des informations exactes et complètes lors de la réservation.</p>
				<p>La réservation est confirmée à la réception d'un acompte ou d'une garantie de paiement valide.</p>

				<h2 class=" my-4 py-2" style="color:#B8860B">3. Tarifs et Paiement</h2>
				<p>Les tarifs des chambres sont indiqués en euros et incluent les taxes applicables. Le paiement peut être effectué en espèces, par carte de crédit ou par virement bancaire.</p>
				<p>Toute modification de réservation peut entraîner des frais supplémentaires.</p>

				<h2 class=" my-4 py-2" style="color:#B8860B">4. Annulation et Modification</h2>
				<p>4.1 Annulation</p>
				<p>En cas d'annulation, des frais peuvent s'appliquer en fonction de la politique d'annulation en vigueur. Le Client est invité à consulter les conditions d'annulation lors de la réservation.</p>
				<p>4.2 Modification</p>
				<p>Toute modification de réservation est soumise à disponibilité et peut entraîner des frais supplémentaires.</p>

				<h2 class=" my-4 py-2" style="color:#B8860B">5. Responsabilité</h2>
				<p>Le Vendeur décline toute responsabilité en cas de vol, perte ou dommage des biens du Client pendant son séjour à l'hôtel.</p>
				<p>Le Client est responsable de tout dommage causé à la propriété de l'hôtel pendant son séjour.</p>

				<h2 class=" my-4 py-2" style="color:#B8860B">6. Confidentialité</h2>
				<p>Les données personnelles fournies par le Client lors de la réservation sont traitées conformément à la politique de confidentialité de l'hôtel. Ces données ne seront pas partagées avec des tiers sans le consentement préalable du Client.</p>

				<h2 class=" my-4 py-2" style="color:#B8860B">7. Droit applicable et litiges</h2>
				<p>Les présentes CGV sont régies par le droit français. En cas de litige, les tribunaux compétents seront ceux du ressort de l'hôtel HotelHouse.</p>

				<h2 class=" my-4 py-2" style="color:#B8860B">8. Modification des CGV</h2>
				<p>Le Vendeur se réserve le droit de modifier les présentes CGV à tout moment. Les modifications seront applicables dès leur publication sur le site web de l'hôtel.</p>

				<h2 class=" my-4 py-2" style="color:#B8860B">9. Contact</h2>
				<p>Pour toute demande d'information ou réclamation concernant les présentes CGV, veuillez nous contacter aux coordonnées suivantes :</p>
				<p>Nom de l'hôtel : HotelHouse</p>
				<p>Adresse : 123 Rue des Hôtes, 75000 Paris, France</p>
				<p>Téléphone : +XX XXX XXX XXX</p>
				<p>Email : info@hotelhouse.com</p>
			</div>
		</div>
	</div>
{% endblock %}

templates/app/contact.html.twig
{% extends "base.html.twig" %}

{% block title %}Nous Contacter
{% endblock %}

{% block body %}
	<div class="container">
		<div class="p-5">
			<h1 class="text-center my-4 text-uppercase border-bottom py-2" style="color:#B8860B">Contacter l'hôtel</h1>

			<form action="{{ path('message') }}" method="post">
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<label for="nom" style="color:#B8860B">Nom:</label>
							<input type="text" class="form-control" id="nom" name="nom" required>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label for="prenom" style="color:#B8860B">Prénom:</label>
							<input type="text" class="form-control" id="prenom" name="prenom" required>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<label for="email" style="color:#B8860B">Email:</label>
							<input type="email" class="form-control" id="email" name="email" required>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label for="sujet" style="color:#B8860B">Sujet:</label>
							<input type="text" class="form-control" id="sujet" name="sujet" required>
						</div>
					</div>
				</div>
				<div class="form-group">
					<label for="categorie" style="color:#B8860B">Catégorie:</label>
					<select class="form-control" id="categorie" name="categorie" required>
						<option value="chambre">Chambre</option>
						<option value="restaurant">Restaurant</option>
						<option value="spa">Spa</option>
						<option value="sujet_general">Sujet Général</option>
					</select>
				</div>
				<div class="form-group">
					<label for="message" style="color:#B8860B">Message:</label>
					<textarea class="form-control" id="message" name="message" rows="5" required></textarea>
				</div>
				<div class="text-center mt-5">
					<button type="submit" class="btn-css w-50">Envoyer</button>
				</div>
			</form>

		</div>
	</div>
{% endblock %}

templates/app/hotel.html.twig
{% extends "base.html.twig" %}

{% block title %}
	Hôtel
{% endblock %}

{% block body %}
	<body class="bg-hotel text-dark">
		<div class="container">
		<h1 class="text-center my-4 text-uppercase border-bottom py-2" style="color:#B8860B">A propos de nous</h1>
			<div class="row mt-5 rounded">
				<div class="col-md-5">
					<div class="row">
						<div class="col-md-6">
							<img src="{{ asset('assets/img/aboutushotel.jpg')}}" alt="" class="mx-2 mb-2 rounded-circle scale" style="object-fit:cover;">
							<img src="{{ asset('assets/img/aboutushotel2.jpg')}}" alt="" style="object-fit:cover;" class="mx-2 rounded-circle scale">
						</div>
						<div class="col-md-6">
							<img src="{{ asset('assets/img/aboutushotel3.jpg')}}" alt=""  style="object-fit:cover;" class="mb-2 rounded-circle scale">
							<img src="{{ asset('assets/img/aboutushotel4.jpg')}}" alt="" class="rounded-circle scale" style="object-fit:cover;">
						</div>
					</div>
				</div>

				<div class="col-md-7 d-flex justify-content-center align-items-center flex-column bg-light rounded p-5 hover-transparent">
					<h2 class="text-shadow mb-3" style="color:#B8860B">Qui sommes-nous</h2>
					<p class="text-shadow mt-3">Bienvenue chez HotelHouse, votre destination pour des séjours inoubliables. Depuis notre création, nous nous engageons à offrir à nos clients une expérience exceptionnelle dans l'industrie de l'hôtellerie.
						<br>

						Chez HotelHouse, nous sommes passionnés par l'hospitalité et nous nous efforçons de vous offrir un hébergement de qualité, un service personnalisé et des installations de premier ordre.
						<br>

						Notre équipe dévouée est là pour vous accueillir chaleureusement et veiller à ce que chaque détail de votre séjour soit pris en compte.
						<br>

						Des chambres élégantes, des restaurants raffinés, des espaces de réunion modernes et bien plus encore - tout est conçu pour vous offrir une expérience mémorable.
						<br>

						HotelHouse est là pour vous accueillir lors de votre prochain voyage et vous offrir des moments de détente et de plaisir.
						<br>

						Faites confiance à notre expertise et découvrez l'univers HotelHouse lors de votre prochaine escapade."
						<br>

						J'espère que cette version plus courte répond à vos attentes.
					</p>
				</div>
			</div>
			<div class="">
				<div class="row">
					<div class="col-md-7 d-flex justify-content-center align-items-center flex-column mt-5 mb-3 bg-light rounded p-5 hover-transparent">
						<h2 style="color:#B8860B" class="mb-3">Notre localisation :</h2>
						<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2624.0447200220447!2d2.3440240926751192!3d48.87642402553321!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66e6b328ce1a1%3A0x713ae68f46c8435b!2sH%C3%B4tel%20Paris%20Lafayette!5e0!3m2!1sfr!2sfr!4v1687857420959!5m2!1sfr!2sfr" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
						<p class="mt-4">L'accès à notre lieu est facile et pratique, que ce soit en voiture, en bus, en train ou même à pied. Nous sommes idéalement situés à proximité de différentes options de transport. Vous pouvez venir en voiture en utilisant les voies principales et vous trouverez un parking à proximité. Si vous préférez les transports en commun, plusieurs lignes de bus et de train desservent notre emplacement. De plus, si vous souhaitez profiter d'une agréable promenade, notre lieu est accessible à pied depuis divers points d'intérêt de la ville.</p>
					</div>
					<div class="col-md-5 mt-5">
							<img src="{{ asset('assets/img/hotelstreet.jpg')}}" alt="" style="height:745px;" class="hover-transparent">
					</div>
				</div>

			</div>

			<div class=" my-5 bg-light rounded p-5 hover-transparent">
				<h2 class="text-center mt-5 mb-4" style="color:#B8860B">Contactez l'hôtel</h2>
				<div class="mb-3">
					<label for="message" class="form-label">Message :</label>
					<textarea id="message" name="message" class="form-control" rows="5" style="resize:none;" required></textarea>
				</div>
				<div class="text-center mt-5">
					<a href="mailto:contact@votre-etablissement.com?subject=Contact depuis le site de l'hôtel&body=Bonjour," class="btn-css mb-5 ">Envoyer un e-mail</a>
				</div>
			</div>

		</div>
	</body>

</div></body>{% endblock %}

templates/app/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil
{% endblock %}

{% block body %}

<main>
	<section class="hero">
		<h1 class="text-center fst-italic p-3" style="color:#B8860B">HouseHôtel <i class="bi bi-dice-6-fill"></i>,
			<br>
			comme à la maison!</h1>

		<div id="carouselExampleCaptions" class="carousel slide">
			<div class="carousel-indicators">
				<button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
				<button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
				<button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
			</div>
			<div class="carousel-inner">
				{% for slide in slides %}
					<div class="carousel-item{% if loop.first %} active{% endif %}">
						<img src="{{ asset('assets/img/carousel/' ~ slide.photo) }}" class="d-block w-100" alt="Slide {{ loop.index }}" style="object-fit:cover;width:500px;height:800px">
						<div class="carousel-caption d-none d-md-block p-5">
							<a href="{{ path('rooms') }}" class="btn-css text-light">Réserver dès maintenant</a>
						</div>
					</div>
				{% endfor %}
			</div>
			<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slFide="prev">
				<span class="carousel-control-prev-icon" aria-hidden="true"></span>
				<span class="visually-hidden">Previous</span>
			</button>
			<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
				<span class="carousel-control-next-icon" aria-hidden="true"></span>
				<span class="visually-hidden">Next</span>
			</button>
		</div>
	</section>
	<div class="container text-center">
		<h2 class="text-center my-4 text-uppercase border-bottom py-2" style="color:#B8860B">Les services de l'hôtel</h2>
		<div class="cards">
			<div class="card card-1">
				<div class="img-stock">
					<img src="{{asset("assets/img/room2.jpg")}}" alt="" class="services-img">
				</div>
				<h3 style="color:#B8860B">Chambres</h3>
				<p>Découvrez un confort absolu et une élégance sans pareil dans nos chambres luxueuses. Chaque détail a été soigneusement pensé pour créer un environnement propice à la détente et au bien-être. Des matériaux de haute qualité, un design moderne et une ambiance chaleureuse se combinent pour offrir une expérience unique. Profitez d'un espace spacieux, d'un lit confortable et d'équipements de pointe pour un séjour inoubliable.</p>
				<a href="{{ path('rooms') }}" class="btn-css">Nos chambres</a>
			</div>
			<div class="card card-2">
				<div class="img-stock">
					<img src="{{asset('assets/img/restaurant2.jpg')}}" alt="" class="services-img">
				</div>
				<h3 style="color:#B8860B">Restaurant</h3>
				<p>Découvrez une expérience culinaire exceptionnelle dans notre restaurant de renommée mondiale. Nos chefs talentueux utilisent les meilleurs ingrédients frais et locaux pour créer des plats savoureux qui raviront vos papilles. Que vous soyez amateur de cuisine traditionnelle ou de mets plus audacieux et créatifs, notre carte propose une variété de choix qui saura satisfaire toutes les préférences. qui saura satisfaire toutes les préférences.</p>
				<a href="{{ path('restaurant') }}" class="btn-css">Notre restaurant</a>
			</div>
			<div class="card card-3">
				<div class="img-stock">
					<img src="{{asset('assets/img/spa2.jpg')}}" alt="" class="services-img">
				</div>
				<h3 style="color:#B8860B">Spa</h3>
				<p>Détendez-vous et ressourcez-vous dans notre luxueux spa. Notre équipe de professionnels qualifiés est là pour vous offrir une expérience de bien-être inoubliable. Laissez-vous dorloter avec une gamme de soins apaisants et revitalisants, allant des massages relaxants aux traitements de beauté raffinés. Profitez d'un environnement paisible et harmonieux où vous pourrez échapper au stress de la vie quotidienne et vous revitaliser en profondeur.</p>
				<a href="{{ path('spa')}}" class="btn-css">Notre spa</a>
			</div>
		</div>
		<div class="m3-5 mb-3">
			<h2 style="color:#B8860B" class="mb-3 text-uppercase border-bottom py-2">Notre localisation</h2>
			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2624.0447200220447!2d2.3440240926751192!3d48.87642402553321!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66e6b328ce1a1%3A0x713ae68f46c8435b!2sH%C3%B4tel%20Paris%20Lafayette!5e0!3m2!1sfr!2sfr!4v1687857420959!5m2!1sfr!2sfr" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
			<p class="mt-4">L'accès à notre lieu est facile et pratique, que ce soit en voiture, en bus, en train ou même à pied.
				<br>
				Nous sommes idéalement situés à proximité de différentes options de transport.
				<br>Vous pouvez venir en voiture en utilisant les voies principales et vous trouverez un parking à proximité.
				<br>
				Si vous préférez les transports en commun, plusieurs lignes de bus et de train desservent notre emplacement.
				<br>
				De plus, si vous souhaitez profiter d'une agréable promenade, notre lieu est accessible à pied depuis divers points d'intérêt de la ville.</p>
		</div>
	</div>
</div>

<div class="container">
	<div class="p-5">
		<h2 class="text-center mt-1 mb-4 text-uppercase border-bottom py-2" style="color:#B8860B">Contactez l'hôtel</h2>
		<form action="{{ path('message') }}" method="post">
			<div class="row">
				<div class="col-md-6">
					<div class="form-group">
						<label for="nom" style="color:#B8860B">Nom:</label>
						<input type="text" class="form-control" id="nom" name="nom" required>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<label for="prenom" style="color:#B8860B">Prénom:</label>
						<input type="text" class="form-control" id="prenom" name="prenom" required>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					<div class="form-group">
						<label for="email" style="color:#B8860B">Email:</label>
						<input type="email" class="form-control" id="email" name="email" required>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<label for="sujet" style="color:#B8860B">Sujet:</label>
						<input type="text" class="form-control" id="sujet" name="sujet" required>
					</div>
				</div>
			</div>
			<div class="form-group">
				<label for="categorie" style="color:#B8860B">Catégorie:</label>
				<select class="form-control" id="categorie" name="categorie" required>
					<option value="chambre">Chambre</option>
					<option value="restaurant">Restaurant</option>
					<option value="spa">Spa</option>
					<option value="sujet_general">Sujet Général</option>
				</select>
			</div>
			<div class="form-group">
				<label for="message" style="color:#B8860B">Message:</label>
				<textarea class="form-control" id="message" name="message" rows="5" required></textarea>
			</div>
			<div class="text-center mt-5">
				<button type="submit" class="btn-css w-50">Envoyer</button>
			</div>
		</form>

	</div>
</div></div></div><</div></main> {% endblock %}

templates/app/rent.html.twig
{% extends "base.html.twig" %}

{% block title %}Réserver votre chambre
{% endblock %}

{% block body %}

	<div id="carouselExampleCaptions" class="carousel slide">
		<div class="carousel-indicators">
			<button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
			<button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
			<button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
		</div>
		<div class="carousel-inner">
			<div class="carousel-item active">
				<img src="{{ asset("assets/img/carousel/carouselroom1.jpg") }}" class="d-block w-100" style="height:400px; object-fit:cover;" alt="...">
			</div>
			<div class="carousel-item">
				<img src="{{ asset("assets/img/carousel/carouselroom2.jpg") }}" class="d-block w-100" style="height:400px; object-fit:cover;" alt="...">
			</div>
			<div class="carousel-item">
				<img src="{{ asset("assets/img/carousel/carouselroom3.jpg") }}" class="d-block w-100" style="height:400px; object-fit:cover;" alt="...">

			</div>
		</div>
		<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
			<span class="carousel-control-prev-icon" aria-hidden="true"></span>
			<span class="visually-hidden">Previous</span>
		</button>
		<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
			<span class="carousel-control-next-icon" aria-hidden="true"></span>
			<span class="visually-hidden">Next</span>
		</button>
	</div>
	
	<div class="container mt-5">
	<h3 class="mb-3 text-uppercase border-bottom py-2" style="font-size:42px; color:#B8860B">{{chambre.titre}}</h3>
	<h2 class="text-center my-4" style="color:#B8860B">Réserver dès maintenant</h2>
		{{ form_start(form, {
    novalidate: 'novalidate'
}) }}


		<div class="row">
			<div class="col-6">
				{{ form_row(form.date_arrive) }}
			</div>
			<div class="col-6">
				{{ form_row(form.date_depart) }}
			</div>
		</div>

		<div class="row">
			<div class="col-6  mb-5">
				<small>La
					{{ chambre.titre }}
					est au prix de
					<span style="color:#B8860B">{{ chambre.prixJournalier }}€</span>
					par nuit</small>
			</div>
		</div>

		<div class="row">
			<div class="col-6">
				{{ form_row(form.prenom) }}
			</div>
			<div class="col-6">
				{{ form_row(form.nom) }}
			</div>
		</div>

		<div class="row">
			<div class="col-6">
				{{ form_row(form.telephone) }}
			</div>
			<div class="col-6">
				{{ form_row(form.email) }}
			</div>
		</div>

		<input type="submit" value="Envoyer" class=" w-100 my-5 btn-css">
		{{ form_end(form) }}

		<h2 class="text-center" style="color:#B8860B">Equipement et informations</h2>
		<p class="mt-3">{{chambre.descriptionLongue|striptags }}</p>

	</div>

{% endblock %}

templates/app/rooms.html.twig
{% extends "base.html.twig" %}

{% block title %}Chambres
{% endblock %}

{% block body %}
	<div class="container">
	<h1 class="text-center mt-5 text-uppercase border-bottom py-2" style="color:#B8860B">Nos chambres</h1>
		{% for room in rooms %}
			<a class="" href="{{ path('rent', {id : room.id}) }}">
				<div class="row my-5 p-5 room-border hover-transparent" >
					{% if room.titre == "Chambre Confort" %}
						<div class="col-6">
							<img src="{{ asset("assets/img/chambres/" ~ room.photo) }}" alt="" class="img-fluid" style="width:500px;height:300px">
						</div>
						<div class="col-6 d-flex flex-column align-items-center justify-content-center">
							<h1 style="color:#B8860B">{{ room.titre }}</h1>
							<p>{{ room.descriptionCourte|striptags }}</p>
						</div>
					{% else %}
						<div class="col-6 d-flex flex-column align-items-center justify-content-center">
							<h1 style="color:#B8860B">{{ room.titre }}</h1>
							<p>{{ room.descriptionCourte|striptags }}</p>
						</div>
						<div class="col-6">
							<img src="{{ asset("assets/img/chambres/" ~ room.photo) }}" alt="" class="img-fluid" style="width:500px;height:300px">
						</div>
					{% endif %}
				</div>
			</a>
		{% endfor %}
	</div>
{% endblock %}