src/Entity/Avis.php
<?php

namespace App\Entity;

use App\Repository\AvisRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AvisRepository::class)]
class Avis
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $commentaire = null;

    #[ORM\Column(length: 255)]
    private ?string $notation = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    #[ORM\Column(length: 255)]
    private ?string $categorie = null;

    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(string $commentaire): static
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    public function getNotation(): ?string
    {
        return $this->notation;
    }

    public function setNotation(string $notation): static
    {
        $this->notation = $notation;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): static
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): static
    {
        $this->categorie = $categorie;

        return $this;
    }
}

src/Form/AvisType.php
<?php

namespace App\Form;

use App\Entity\Avis;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class AvisType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email', EmailType::class, [
                'attr' => [
                    'placeholder' => "Entrez l'email"
                ]
            ])
            ->add('categorie', ChoiceType::class, [
                'choices' => [
                    'Hotel' => 'Hotel',
                    'Chambres' => 'Chambres',
                    'Restaurant' => 'Restaurant',
                    'Soin' => 'Soin',
                ],
                'placeholder' => 'Choisissez la catégorie',
            ])
            ->add('nom', TextType::class, [
                'attr' => [
                    'placeholder' => "Entrez le nom"
                ]
            ])
            ->add('prenom', TextType::class, [
                'attr' => [
                    'placeholder' => "Entrez le prénom"
                ]
            ])
            ->add('commentaire', TextareaType::class, [
                'attr' => [
                    'placeholder' => "Entrez votre commentaire",
                    'class' => 'form-control',
                    'style' => 'resize: none; height: 150px; font-size: 14px; padding: 10px;',
                ],
                'constraints' => [
                    new NotBlank([
                        'message' => 'Veuillez entrer un commentaire.',
                    ]),
                    new Length([
                        'min' => 10,
                        'minMessage' => 'Le commentaire doit contenir au moins {{ limit }} caractères.',
                    ]),
                ],
            ])
            ->add('notation', ChoiceType::class, [
                'choices' => [
                    '1' => 1,
                    '2' => 2,
                    '3' => 3,
                    '4' => 4,
                    '5' => 5,
                ],
                'placeholder' => 'Choisissez une note / 5',
            ])
            // ->add('date_enregistrement')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Avis::class,
        ]);
    }
}

src/Controller/AvisController.php
<?php

namespace App\Controller;

use App\Entity\Avis;
use App\Form\AvisType;
use App\Repository\AvisRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AvisController extends AbstractController
{
    #[Route('/avis', name: 'avis')]
    public function index(Request $request, EntityManagerInterface $manager, AvisRepository $repo): Response
    {
        $categories = $repo->findDistinctCategories(); // Récupérer les catégories distinctes depuis le repository
        
        $selectedCategory = $request->query->get('categorie'); // Récupérer la catégorie sélectionnée depuis la requête
    
        // Récupérer les avis en fonction de la catégorie sélectionnée
        $comments = $selectedCategory ? $repo->findByCategorie($selectedCategory) : $repo->findAll();
    
        $comments = array_reverse($comments);
    
        $avis = new Avis;
        $form = $this->createForm(AvisType::class, $avis);
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            $avis->setDateEnregistrement(new \DateTime);
            $manager->persist($avis);
            $manager->flush();
            $this->addFlash('success', "Votre avis a bien été envoyé");
            return $this->redirectToRoute('avis');
        }
    
        return $this->render('avis/index.html.twig', [
            'form' => $form,
            'avis' => $comments,
            'categories' => $categories,
            'selectedCategory' => $selectedCategory
        ]);
    }    
}

templates/avis/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Avis
{% endblock %}

{% block body %}
	<body>
		<div class="container">
		<h1 class="text-center my-4 text-uppercase border-bottom py-2" style="color:#B8860B">Avis sur HouseHôtel et ses services</h1>
			<div class="row">
				<div
					class="col-9">
					<!-- Formulaire de sélection de catégorie -->
					<form action="{{ path('avis') }}" method="GET" class="mb-4">
						<p class="my-5 text-center h3" style="color:#B8860B">Nombre d'avis clients :
							{{ avis|length }}</p>
						<div class="form-group">
							<label for="categorie">Sélectionnez une catégorie :</label>
							<select name="categorie" id="categorie" class="form-control">
								<option value="">Toutes les catégories</option>
								{% for categorie in categories %}
									<option value="{{ categorie|join }}" {% if categorie == selectedCategory %} selected {% endif %}>{{ categorie|join }}</option>
								{% endfor %}
							</select>
						</div>
						<button type="submit" class="btn-css mt-3 w-100">Filtrer</button>
					</form>

					<!-- Affichage des avis filtrés -->

					{% for item in avis %}
						<div class="hover-transparent p-3 mt-3 rounded" style="border: 1px solid #B8860B">
							<h2>Par :<span style="color:#B8860B">
									{{ item.email }}</span>
							</h2>
							<h3 class="text-center my-3">Catégorie :
								<span style="color:#B8860B">{{ item.categorie }}</span>
							</h3>
							<p class="text-center mx-auto">Notation:
								<span>
									{% for i in range(1, 5) %}
										{% if i <= item.notation %}
											<span class="bi bi-star-fill text-warning"></span>
										{% else %}
											<span class="bi bi-star-fill text-secondary"></span>
										{% endif %}
									{% endfor %}
								</span>
							</p>
							<div class="border border-1 border-dark p-3">
								<p>De : {{ item.nom|upper}}
									{{ item.prenom}}</p>
								<p> <span class="text-decoration-underline">Commentaire :</span> <br>{{ item.commentaire }}</p>
							</div>
							<div>
								<p class="text-end fst-italic mt-3">{{ item.dateEnregistrement|date('d/m/Y à H:i:s') }}</p>
							</div>
						</div>
					{% endfor %}
				</div>

				<div class="col-3 mt-5">
					<button id="afficherFormulaire" class="btn-css">Cliquez ici pour laisser un commentaire</button>
					<div id="formulaire" style="display: none;">
						{{ form_start(form) }}
						{{ form_row(form.categorie) }}
						{{ form_row(form.email) }}
						{{ form_row(form.nom) }}
						{{ form_row(form.prenom) }}
						{{ form_row(form.notation) }}
						{{ form_row(form.commentaire) }}
						<button type="submit" class="btn btn-warning">Envoyer Avis</button>
						{{ form_end(form) }}
					</div>
				</div>
			</div>
		</div>

		<script>
			document.getElementById("afficherFormulaire").addEventListener("click", function () {
			const formulaire = document.getElementById("formulaire");
			if (formulaire.style.display === "none") {
			formulaire.style.display = "block";
			} else {
			formulaire.style.display = "none";
			}
			});
		</script>
	</body>
{% endblock %}